# version: '3.8'

services:
  # El motor de almacenamiento (Redis)
  cache_redis:
    image: redis:latest
    container_name: cache_redis
    ports:
      - "6379:6379"
    # Aquí ya configuramos las políticas (LRU y 50mb)
    command: redis-server --maxmemory 50mb --maxmemory-policy allkeys-lru 

  # El motor de cálculo pesado (API Flask)
  generador_respuestas:
    build: ./generador_respuestas  # Le dice a Docker que busque el Dockerfile en esa carpeta
    container_name: generador_respuestas
    ports:
      - "5000:5000"
    depends_on:
      - cache_redis
    volumes:
      - ./967_buildings.csv.gz:/app/967_buildings.csv.gz
    healthcheck:
      # Hace un ping al endpoint /q1 usando una librería nativa de Python
      test: ["CMD-SHELL", "python -c 'import urllib.request; urllib.request.urlopen(\"http://127.0.0.1:5000/q1\")' || exit 1"]
      interval: 5s       # Cada 10 segundos revisa si ya levantó
      timeout: 5s         # Espera máximo 5 segundos por el intento
      retries: 15         # Intenta hasta 15 veces (150 segundos de paciencia)
      start_period: 5s   # Espera 15s de gracia antes de empezar a chequear

  # (API Flask)

  # El recolector de estadísticas
  almacenador_metricas:
    build: ./almacenador_metricas
    container_name: almacenador_metricas
    ports:
      - "6000:6000"
  # El generador de tráfico    
  generador_trafico:
    build: ./generador_trafico
    container_name: generador_trafico
    environment:
      - DISTRIBUCION=zipf      # Cambiar "distribución" con el valor (zipf o uniforme) para cambiar distribución de tráfico
      - TASA_ESPERA=1        # 0.1 significa 10 peticiones por segundo. bajar este punto estresa más al sistema. subirlo lo hace más relajado.
      - PYTHONUNBUFFERED=1
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  consumidores_kafka:
    build: ./consumidor_kafka
    depends_on:
      - kafka
      - cache_redis
      - generador_respuestas
    deploy:
      replicas: 1
    environment:
      - PYTHONUNBUFFERED=1
  consumidor_reintentos:
    build: ./consumidor_reintentos
    depends_on:
      - kafka
      - generador_respuestas
    environment:
      - PYTHONUNBUFFERED=1
    